In [1]:
import numpy as np

In [11]:
a = np.array([[1., 0., 0.],
              [0., 1., 2.]])

print("Quantidade de dimensões/ axes: ", a.ndim)
print("Quantidade de linhas/colunas", a.shape)
print("Quantidade total de elementos: ", a.size)

Quantidade de dimensões/ axes:  2
Quantidade de linhas/colunas (2, 3)
Quantidade total de elementos:  6


In [22]:
lista_de_tuplas = [(i, i+1) for i in range(1,10,2)]
a = np.array(lista_de_tuplas)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
a = np.zeros((3,4))
b = np.ones((5,3))
c = np.empty((5,5))
a, b, c

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         8.01092457e-307, 7.56587585e-307],
        [1.37961302e-306, 1.05699242e-307, 1.95821439e-306,
         9.34609790e-307, 6.89807188e-307],
        [2.22522597e-306, 6.89811602e-307, 1.69121096e-306,
         6.23058028e-307, 6.23053954e-307],
        [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
         1.86921143e-306, 6.23061763e-307],
        [1.42421160e-306, 1.11261027e-306, 2.22522596e-306,
         1.42410974e-306, 2.56761491e-312]]))

In [41]:
a = np.arange(0,10,2)
b = np.linspace(1, 4, 4)

a, b

(array([0, 2, 4, 6, 8]), array([1., 2., 3., 4.]))